#!/usr/bin/env python3
"""Bridge: voice-memo-pipeline → ocean-knowledge-intake.

Drop-in INTAKE_SCRIPT that transcribes each staged .m4a with the ``whisper``
CLI and then files the transcript into ocean-knowledge-intake via its
``voice_memo`` adapter.

The pipeline calls this as:

    intake-to-ocean.py --model <whisper-model> <file1> [<file2> ...]

Environment variables
---------------------
OCEAN_INTAKE_DIR
    Absolute path to the ocean-knowledge-intake checkout.
    The adapter is imported from there at runtime — no install, no
    sys-path manipulation beyond this one addition.
    Required (no default — avoids hardcoding user-specific paths).

OCEAN_ACTOR
    The ``actor`` field written into every envelope.
    Defaults to ``"eric"`` (the RT operator who dictates the memo).

OCEAN_SCOPE
    The ``access_scope`` written into every envelope.
    Defaults to ``"team"``.  Allowed values: team | finance | leadership | private.

INTAKE_DRY_RUN
    Set to any non-empty value to stub transcription with a fixture string
    and print the envelope JSON instead of submitting it to the store.
    Useful for testing this script without Whisper or Ollama installed.

Usage
-----
# Normal (requires whisper, ffmpeg, and Ollama):
export OCEAN_INTAKE_DIR=/path/to/ocean-knowledge-intake
python3 examples/intake-to-ocean.py --model small /tmp/memo.m4a

# Dry run (no dependencies needed):
INTAKE_DRY_RUN=1 OCEAN_INTAKE_DIR=/path/to/ocean-knowledge-intake \\
    python3 examples/intake-to-ocean.py --model small /tmp/fake.m4a

# Wire into the pipeline via env var:
export VOICE_MEMO_INTAKE_SCRIPT=/path/to/downloading-from-the-source/examples/intake-to-ocean.py
export OCEAN_INTAKE_DIR=/path/to/ocean-knowledge-intake
python3 voice-memo-pipeline.py
"""
from __future__ import annotations

import argparse
import dataclasses
import json
import os
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

# ---------------------------------------------------------------------------
# Config from environment
# ---------------------------------------------------------------------------

_OCEAN_DIR_RAW = os.environ.get("OCEAN_INTAKE_DIR", "")
OCEAN_ACTOR = os.environ.get("OCEAN_ACTOR", "eric")
OCEAN_SCOPE = os.environ.get("OCEAN_SCOPE", "team")
DRY_RUN = bool(os.environ.get("INTAKE_DRY_RUN", ""))

# Fixture transcript used when DRY_RUN=1 so the script is fully testable
# without Whisper or any audio file on disk.
_DRY_RUN_FIXTURE = (
    "[DRY-RUN FIXTURE] This is a stub transcript generated by intake-to-ocean.py "
    "when INTAKE_DRY_RUN=1. No Whisper was invoked."
)


# ---------------------------------------------------------------------------
# Transcription
# ---------------------------------------------------------------------------


def _run_whisper(audio_path: Path, model: str) -> str:
    """Transcribe *audio_path* with the ``whisper`` CLI; return plain text."""
    if not audio_path.exists():
        print(f"  ✗ audio file not found: {audio_path}", file=sys.stderr)
        return ""

    with tempfile.TemporaryDirectory() as tmp:
        cmd = [
            "whisper", str(audio_path),
            "--model", model,
            "--output_format", "txt",
            "--output_dir", tmp,
            "--language", "en",
            "--fp16", "False",
        ]
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=900)
        except FileNotFoundError:
            print(
                "  ✗ whisper not found on PATH.\n"
                "    Install with:  pip install -U openai-whisper\n"
                "    Or brew:       brew install openai-whisper",
                file=sys.stderr,
            )
            return ""
        except subprocess.TimeoutExpired:
            print(f"  ✗ whisper timed out after 900 s on {audio_path.name}", file=sys.stderr)
            return ""

        if result.returncode != 0:
            print(f"  ✗ whisper exited {result.returncode}: {result.stderr[:500]}", file=sys.stderr)
            return ""

        txt_file = Path(tmp) / f"{audio_path.stem}.txt"
        if not txt_file.exists():
            print(f"  ✗ whisper produced no .txt in {tmp}", file=sys.stderr)
            return ""
        return txt_file.read_text(encoding="utf-8").strip()


def transcribe(audio_path: Path, model: str) -> str:
    """Return transcript text (empty string on failure)."""
    if DRY_RUN:
        return _DRY_RUN_FIXTURE
    return _run_whisper(audio_path, model)


# ---------------------------------------------------------------------------
# Ocean adapter import
# ---------------------------------------------------------------------------


def _load_ocean_adapter():
    """Import the voice_memo adapter from OCEAN_INTAKE_DIR at runtime.

    Returns the adapter callable, or exits with a clear error message.
    """
    if not _OCEAN_DIR_RAW:
        print(
            "  ✗ OCEAN_INTAKE_DIR is not set.\n"
            "    Point it at your ocean-knowledge-intake checkout:\n"
            "      export OCEAN_INTAKE_DIR=/path/to/ocean-knowledge-intake",
            file=sys.stderr,
        )
        sys.exit(2)

    ocean_dir = Path(_OCEAN_DIR_RAW).expanduser().resolve()
    if not ocean_dir.is_dir():
        print(
            f"  ✗ OCEAN_INTAKE_DIR does not exist: {ocean_dir}",
            file=sys.stderr,
        )
        sys.exit(2)

    if str(ocean_dir) not in sys.path:
        sys.path.insert(0, str(ocean_dir))

    try:
        import adapters as _adapters  # noqa: PLC0415 (runtime import by design)
    except ImportError as exc:
        print(
            f"  ✗ Could not import ocean-knowledge-intake adapters from {ocean_dir}:\n"
            f"    {exc}",
            file=sys.stderr,
        )
        sys.exit(2)

    adapter = getattr(_adapters, "voice_memo", None)
    if adapter is None:
        print(
            f"  ✗ ocean-knowledge-intake adapters module at {ocean_dir} "
            "has no 'voice_memo' function.",
            file=sys.stderr,
        )
        sys.exit(2)

    return adapter


# ---------------------------------------------------------------------------
# Envelope submission
# ---------------------------------------------------------------------------


def _envelope_as_dict(env) -> dict:
    """Convert a RawEnvelope dataclass to a plain dict for JSON printing."""
    try:
        return dataclasses.asdict(env)
    except Exception:  # noqa: BLE001
        # Fallback: manually pull __dict__ if not a dataclass
        return {k: str(v) for k, v in vars(env).items()}


def submit(transcript: str, audio_path: Path, occurred_at: str, adapter) -> None:
    """Build a RawEnvelope and submit it (or print JSON in DRY_RUN mode)."""
    env = adapter(
        actor=OCEAN_ACTOR,
        body=transcript,
        occurred_at=occurred_at,
        access_scope=OCEAN_SCOPE,
    )

    if DRY_RUN:
        print(json.dumps(_envelope_as_dict(env), indent=2, default=str))
        return

    # Import store and normalize from the ocean directory (already on sys.path).
    try:
        import store  # noqa: PLC0415
        import normalize as _norm_mod  # noqa: PLC0415
    except ImportError as exc:
        print(
            f"  ✗ Could not import ocean-knowledge-intake store/normalize: {exc}",
            file=sys.stderr,
        )
        sys.exit(2)

    store.init_db()
    norm = _norm_mod.normalize(env)
    event_id = store.write_event(env, norm)
    n = norm.get("normalized") or {}
    print(f"  filed {event_id[:8]}  [{norm.get('entry_type', '?')}]  {n.get('summary', '')}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Bridge intake: transcribe .m4a with Whisper then file into ocean-knowledge-intake."
        )
    )
    parser.add_argument("files", nargs="+", help="Staged .m4a file(s) from voice-memo-pipeline")
    parser.add_argument(
        "--model",
        default="small",
        help="Whisper model: tiny | base | small | medium | large  (default: small)",
    )
    args = parser.parse_args()

    adapter = _load_ocean_adapter()

    failures = 0
    for raw_path in args.files:
        audio_path = Path(raw_path)
        print(f"→ {audio_path.name}")

        transcript = transcribe(audio_path, args.model)
        if not transcript:
            print(f"  ✗ transcription empty — skipping {audio_path.name}", file=sys.stderr)
            failures += 1
            continue

        # Use file mtime as occurred_at if we cannot inspect the audio metadata.
        if audio_path.exists():
            mtime = audio_path.stat().st_mtime
            occurred_at = datetime.fromtimestamp(mtime, tz=timezone.utc).isoformat()
        else:
            occurred_at = datetime.now(timezone.utc).isoformat()

        try:
            submit(transcript, audio_path, occurred_at, adapter)
        except Exception as exc:  # noqa: BLE001
            print(f"  ✗ submission failed: {exc}", file=sys.stderr)
            failures += 1

    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
